CREATE TABLE accommodation_activity_log
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    accommodation_id    BIGINT                                              NOT NULL,
    accommodation_name  VARCHAR(255)                                        NOT NULL,
    event_type          VARCHAR(255)                                        NOT NULL
);