spring.datasource.url=jdbc:postgresql://localhost:5432/booking
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

JWT_SECRET_KEY=bXktc3VwZXItc2VjcmV0LWp3dC1rZXktZm9yLWJvb2tpbmctYXBwbGljYXRpb24tbmdlLWx1LXByb2R1Y3Rpb24tMjAyNg==

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
