spring.application.name=booking-backend

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

jwt.expiration=864000000
jwt.header=Authorization
jwt.token-prefix=Bearer
jwt.generate-key=False

spring.flyway.enabled=true
spring.profiles.active=dev
